### ISSUE TITLE
Allow Connections to be synced via settings code

### ISSUE THREAD

**Issue by SirWillian** [homothetyhk/RandomizerMod#36] opened 2023-09-15 19:09 UTC
Quickly checking the code for this mod, it seems like it's not currently possible to sync the settings for mods under the Connections page when using a settings code.

Just spent a couple of days confused about why me and my friends couldn't get our randomizer hashes to match even though we were using the same settings code. Ended up reinstalling the game and mods multiple times before trying to delete previously saved settings and finally having it sync. The cause of the issue ended up being that we had different settings for the RandoPlus mod.

Maybe we were at fault by forgetting that there could be settings under the Connections page or (now that I've researched this) we could have used the RandoSettingsManager, but I think it's also reasonable to expect that the settings code would sync all available settings. It seems unnecessary to rely on yet another mod (like RandoSettingsManager) to do this.

**Comment by homothetyhk** [comment] 2023-09-16 18:55
As you note, RandoSettingsManager provides the functionality you are requesting. Unlike the base randomizer, which converts settings directly into a code, RSM handles potentially more complex data by uploading it to a central location and returning a code for downloading the data. All of the features of the base randomizer are designed to fully function in an offline environment, so the two types of settings codes serve different purposes, and the functionality of RSM is out of scope for the base randomizer.

**Closed by homothetyhk** 2023-09-16 18:55 UTC

**Comment by SirWillian** [comment] 2023-09-16 20:49
Sending settings to a server seemed really unnecessary, so I was looking forward to having an offline solution to that (would rather not wait 5s to receive a code). Given how the base mod handles connections, is it really out of scope to sync settings for them? Would you accept a PR that implements such a thing?

**Comment by UncraftedName** [comment] 2023-09-16 23:19
I see no reason why more "complex settings" need to be uploaded to a server and not stored as part of the shared string. Why is that done? It took us days to figure out how to fully remove the randomizer settings (after uninstalling); and this sounds like a very fixable issue.

**Comment by homothetyhk** [comment] 2023-09-16 23:22
For a mod like RandoPlus, it would be easy to append its settings to the settings code. But for other mods, like CustomPoolInjector, where the settings are toggles based on packs of items, locations, etc. created by the user, there is no straightforward way to put the pack data into the settings code. And if one were to try to do so anyway, the settings code length would very quickly exceed common 2000 character limits, even if compressed, making it much less useful. RSM stores all connection settings as json, so it can handle complex settings. The result is too long to paste directly, but it can use the server to handle sharing the file.

Maybe it seems tempting at that point to only support syncing "simple" settings in the code; for the CustomPoolInjector example, only sync the pack toggles, rather than the packs themselves. But then the settings code would be a regression from what RSM is able to sync, and it would be even more difficult to explain to users the subtle distinctions that could cause connections to fail to sync (at least with the current system, the line between base randomizer and connection is very clear, compared to "simple" connection and "complex" connection). 

For those reasons, I think it is very difficult, if not impossible, to extend the settings code to connections in a way that handles those concerns. @BadMagic100 heavily considered the topic in the initial stages of working on RSM, and we ended up agreeing that the server was the only workable solution.

**Comment by BadMagic100** [comment] 2023-09-17 00:37
Yes, extending the code provided by RandomizerMod is not feasible at scale for a variety of reasons, most pertinently that the code is an encoding of the settings, regardless of the complexity of those settings. That means that as the number of connections in the settings grows, the length of the code will also grow without bound. Since the code is intended to be shared in a messaging client e.g. discord which often has a hard character limit, the only reasonable option is to send the settings off somewhere and return a lookup key which others can use to access the settings. I agree that having a partial implementation in RM is probably much more likely to cause confusion than it is to help (I believe, without checking, that the readme also states connection settings are not included with the code).

If you are really really strongly opposed to having your settings synced via a server for some reason RSM also provides a couple of options which can make use of your local file system (specifically, temp profiles are exactly intended to provide the same functionality as the settings code). But then you will have to upload the profile file, and they will have to download it, and it's probably slower than letting the mod handle it for you. If your primary concern is that 5 seconds to receive settings is a very long time, consider how much less time you are spending than doing it by hand (and, realistically, that often pales in comparison to generation times anyway).

**Comment by SirWillian** [comment] 2023-09-17 01:59
For Discord, at least, even if you exceed the character limit, you can still send your message as a file and easily see the whole contents of the file. It should still be possible then to blindly copy and paste your settings, so even with very long codes you'd have about the same UX. I don't know much about other popular messaging clients that are used alongside PC gaming, so maybe thats a real issue that arises for those clients. Perhaps a "read settings from file" could end up working as a solution if you expect people to be able to be online to share any info (this kinda sounds like I'm reinventing Profiles though). I'm also not familiar with mods whose settings can grow as large as you mentioned so I'd probably need to experiment myself to fully understand the situation.

I do realize that it's not as trivial of a problem to solve as I originally thought. My main complaint though is that it wasn't clear when using the mod that this situation was something that could happen. Checking the README now, I also don't see any mention to this. Perhaps a final suggestion would be to mention RSM on the "strongly recommended mods" section of the README and to include something on the UI about Connections not syncing. There should be enough space on the code generation page to fit in a short note/warning.

**Comment by UncraftedName** [comment] 2023-09-17 03:23
Like Willian mentioned, we realize now it's not a trivial problem to solve. But I fully agree that there should be some mention of this somewhere and/or mark RSM as strongly recommended.
